#注意：要保存为utf-8格式
spring: 
   profiles: 
      active: 
      - dev

---
server:
   port: 8081
   
spring: 
   profiles: dev                                    #开发环境
   application: 
      name: config-consumer                         #应用的名称，后续可以通过此名称查找到此服务, 注意：集群时，此处名称必须一致

feign: 
   hystrix: 
      enabled: true                                 # 启用熔断的开关，一定要开启
      
eureka:
   client:                                          # 客户端注册进eureka服务列表内
      register-with-eureka: false                   # false表示不向注册中心注册自己。                                  
      service-url:  
         #eureka服务注册地址
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
 
---
server:
   port: 8081
   
spring: 
   profiles: test                                   #测试环境
   application: 
      name: config-consumer                         #应用的名称，后续可以通过此名称查找到此服务, 注意：集群时，此处名称必须一致

feign: 
   hystrix: 
      enabled: true                                 # 启用熔断的开关，一定要开启
      
eureka:
   client:                                          # 客户端注册进eureka服务列表内
      register-with-eureka: false                   # false表示不向注册中心注册自己。                                  
      service-url:  
         #eureka服务注册地址
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
 
 